# Use an official node runtime as a parent image
FROM node:10

# Set the working directory to /home/app
WORKDIR . 

# Bundle app source
# COPY . /home/app/

# If you are building your code for production
# RUN npm install --only=production
RUN npm install

# Make port 8000 available to the world outside this container
EXPOSE 8000

CMD npm run dev